DROP TABLE Lessons;
DROP TABLE Event_group;
DROP TABLE Teacher_subject;
DROP TABLE Everyday;
DROP TABLE Everyweek;
DROP TABLE Everymonth;
DROP TABLE Events;
DROP TABLE Groups;
DROP TABLE Teachers;
DROP TABLE Subjects;
DROP TABLE Auditories;

DROP DOMAIN event_date_not_null;
DROP DOMAIN event_time_not_null;
DROP DOMAIN event_date_nullable;
DROP DOMAIN event_time_nullable;
DROP DOMAIN name_field;
DROP DOMAIN smallint_not_null_domain;
DROP DOMAIN domain_integer_not_null;